### ISSUE TITLE
Whoops\Exception\ErrorException thrown with message "Undefined variable $value1"

### ISSUE THREAD

**Issue by mhilbert** [kyro46/assAudio#12]
Class class.assAudioGUI.php, function getSolutionOutput:

  $solutiontemplate->setVariable("RESULT_OUTPUT", $value1);
runs into a problem if $value1 is not set because
  if (isset($user_solution["value1"]))
fails.

Environment: ILIAS 8.8, PHP 8.0.30, assAudio 8.0.0

Whoops\Exception\ErrorException thrown with message "Undefined variable $value1"

Stacktrace:
#11 Whoops\Exception\ErrorException in /data_nfs/htdocs/devel8x/Customizing/global/plugins/Modules/TestQuestionPool/Questions/assAudio/classes/class.assAudioGUI.php:278
#10 ilErrorHandling:handlePreWhoops in /data_nfs/htdocs/devel8x/Customizing/global/plugins/Modules/TestQuestionPool/Questions/assAudio/classes/class.assAudioGUI.php:278
#9 assAudioGUI:getSolutionOutput in /data_nfs/htdocs/devel8x/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TstManualScoringQuestion/src/TstManualScoringQuestion.php:795
#8 ILIAS\Plugin\TstManualScoringQuestion\TstManualScoringQuestion:getAnswerDetail in /data_nfs/htdocs/devel8x/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TstManualScoringQuestion/src/TstManualScoringQuestion.php:303
#7 ILIAS\Plugin\TstManualScoringQuestion\TstManualScoringQuestion:modify in /data_nfs/htdocs/devel8x/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TstManualScoringQuestion/src/TstManualScoringQuestion.php:459
#6 ILIAS\Plugin\TstManualScoringQuestion\TstManualScoringQuestion:showTmsqManualScoring in /data_nfs/htdocs/devel8x/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TstManualScoringQuestion/src/TstManualScoringQuestion.php:210
#5 ILIAS\Plugin\TstManualScoringQuestion\TstManualScoringQuestion:performCommand in /data_nfs/htdocs/devel8x/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TstManualScoringQuestion/classes/class.ilTstManualScoringQuestionUIHookGUI.php:115
#4 ilTstManualScoringQuestionUIHookGUI:executeCommand in /data_nfs/htdocs/devel8x/Services/UICore/classes/class.ilCtrl.php:199
#3 ilCtrl:forwardCommand in /data_nfs/htdocs/devel8x/Services/UIComponent/classes/class.ilUIPluginRouterGUI.php:48
#2 ilUIPluginRouterGUI:executeCommand in /data_nfs/htdocs/devel8x/Services/UICore/classes/class.ilCtrl.php:199
#1 ilCtrl:forwardCommand in /data_nfs/htdocs/devel8x/Services/UICore/classes/class.ilCtrl.php:174
#0 ilCtrl:callBaseClass in /data_nfs/htdocs/devel8x/ilias.php:24

**Comment by kyro46** [comment]
Danke für das Feedback. Die Möglichkeit unbeantwortete Fragen in der manuellen Bewertung anzuzeigen fehlte, ließ sich aber beheben, indem die Lösung ab jetzt als Leer initialisiert wird. Ich hoffe das passt so. Ich sehe, dass ein weiteres Plugin zur Bewertung eingesetzt wird. Das probiere ich aus.

**Comment by mhilbert** [comment]
Hallo Christoph,



vielen Dank für den schnellen Fix. So hätte ich es auch gemacht. J



Das Plugin zur manuellen Bewertung erleichtert die Bewertung enorm, weil man nicht jede Antwort einzeln in einem Popup-Dialog bearbeiten muss. Ich habe Dir einen Auszug aus unserer Hilfe zur Nachkorrektur und manuellen Bewertung angehängt, wo Du auch einen Screenshot siehst.



Viele Grüße



  Mirco



Von: Christoph Jobst ***@***.***>
Gesendet: Donnerstag, 25. Januar 2024 08:01
An: kyro46/assAudio ***@***.***>
Cc: Hilbert, Mirco ***@***.***>; Author ***@***.***>
Betreff: Re: [kyro46/assAudio] Whoops\Exception\ErrorException thrown with message "Undefined variable $value1" (Issue #12)



Danke für das Feedback. Die Möglichkeit unbeantwortete Fragen in der manuellen Bewertung anzuzeigen fehlte, ließ sich aber beheben, indem die Lösung ab jetzt als Leer initialisiert wird. Ich hoffe das passt so. Ich sehe, dass ein weiteres Plugin zur Bewertung eingesetzt wird. Das probiere ich aus.
